name: flu
description: Take home assignment for Joyflo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  http: ^1.1.0
  collection: ^1.17.2
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  isolate: ^2.1.1
  fluttertoast: ^8.2.5
  file_picker: ^8.0.0+1
  flutter_image_compress: ^2.2.0
  image: ^4.1.7
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  path: ^1.8.3
  intl: ^0.19.0
  exif: ^3.3.0
  permission_handler: ^11.0.1
  cross_file: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/leaf_left.svg
    - assets/leaf_right.svg
    - assets/operator.svg
    - assets/top_background.svg
    - assets/thumb_up.svg
    - assets/hand_stop_sign.svg
    - assets/chat_cloud.svg
    - assets/thumb_down.svg
    - shorebird.yaml

